[package]
name = "gravity_sim_ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
nalgebra = "0.32.2"
num-bigfloat = "1.6.2"
rayon = "1.7.0"

# [profile.release]
# lto = true